"""Walk every logged run and catalog the unique fight compositions we've
seen, grouped by (chapter, inState, sorted monster names).

Output: knowledge/game/observed_fight_compositions.md — a table showing
each unique composition, the tile-index range where it was seen, and how
many times it's been observed. Useful for deciding which compositions
deserve richer sim modeling (multi-enemy fights where food choice
actually matters).

Usage: python scripts/catalog_fights.py
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path


FULL_RUNS = Path("C:/dev/dontDieAi/data/full_runs")
OUTPUT = Path("C:/dev/dontDieAi/knowledge/game/observed_fight_compositions.md")


def _most_recent_game_json(run_dir: Path, before_seq: int) -> dict | None:
    """Find the most recent itNNN_game.json with sequence prefix <= before_seq."""
    best = None
    best_seq = -1
    for p in run_dir.glob("*_it*_game.json"):
        m = re.match(r"^(\d+)_it\d+_game\.json$", p.name)
        if not m:
            continue
        seq = int(m.group(1))
        if seq <= before_seq and seq > best_seq:
            best_seq = seq
            best = p
    if best is None:
        return None
    try:
        return json.loads(best.read_text(encoding="utf-8"))
    except Exception:
        return None


def _extract_monsters(prefight: dict) -> list:
    state = prefight.get("state") or {}
    monsters = state.get("monsters") or []
    out = []
    for m in monsters:
        if not isinstance(m, dict):
            continue
        out.append({
            "name": m.get("name") or "?",
            "hp": m.get("maxHealth") or m.get("health") or 0,
        })
    return out


def main():
    if not FULL_RUNS.exists():
        print(f"no full_runs dir at {FULL_RUNS}")
        return 1

    # comp_key = (chapter, inState, tuple(sorted monster names))
    # value = {"count": int, "pos_seen": set, "hp_samples": list, "example_run": str}
    comps: dict[tuple, dict] = defaultdict(lambda: {
        "count": 0,
        "pos_seen": set(),
        "hp_samples": [],
        "example_run": None,
        "monster_hps": None,  # captured once, first sighting
    })

    run_dirs = sorted(p for p in FULL_RUNS.iterdir() if p.is_dir())
    prefight_count = 0

    for rdir in run_dirs:
        for pf_path in sorted(rdir.glob("*_b*_prefight.json")):
            m = re.match(r"^(\d+)_b\d+_prefight\.json$", pf_path.name)
            if not m:
                continue
            pf_seq = int(m.group(1))
            try:
                pf = json.loads(pf_path.read_text(encoding="utf-8"))
            except Exception:
                continue

            monsters = _extract_monsters(pf)
            if not monsters:
                continue
            prefight_count += 1

            game = _most_recent_game_json(rdir, pf_seq)
            if game is None:
                continue
            last = game.get("lastSession") or {}
            chapter = last.get("chapter")
            progress = last.get("progress") or {}
            pos = progress.get("currentIndex")
            in_state = progress.get("inState")
            active_path = progress.get("activePath") or "main"

            # Normalize the monster set — sort names, keep count.
            names = sorted(m["name"] for m in monsters)
            names_str = " + ".join(names)
            key = (chapter, in_state, names_str)
            entry = comps[key]
            entry["count"] += 1
            if pos is not None:
                entry["pos_seen"].add(f"{active_path}[{pos}]")
            if entry["monster_hps"] is None:
                entry["monster_hps"] = [(m["name"], m["hp"]) for m in monsters]
                entry["example_run"] = rdir.name

    # Group output by chapter + inState
    grouped: dict[tuple, list] = defaultdict(list)
    for (chapter, in_state, names_str), entry in comps.items():
        grouped[(chapter, in_state)].append((names_str, entry))

    lines = []
    lines.append("# Observed Fight Compositions")
    lines.append("")
    lines.append(f"Auto-generated by `scripts/catalog_fights.py`. Scanned "
                 f"**{len(run_dirs)} run directories**, {prefight_count} "
                 "battle prefights.")
    lines.append("")
    lines.append("Each row is a unique `(chapter, inState, sorted monster "
                 "names)` observed at least once in real play. "
                 "`pos_seen` lists every distinct `<path>[<tile>]` where "
                 "that composition appeared; `n` is the total occurrence "
                 "count. Use this to decide which compositions deserve "
                 "richer sim modeling — multi-enemy fights with real "
                 "food-differentiation potential.")
    lines.append("")
    lines.append("⚠️  `chapter` and `pos` are per-chapter — position resets "
                 "to 0 at each chapter boundary, so `main[8]` in Ch1 ≠ "
                 "`main[8]` in Ch2.")
    lines.append("")

    def _chapter_order(k):
        ch, st = k
        return (ch if ch is not None else 99, st or "")

    for (chapter, in_state) in sorted(grouped.keys(), key=_chapter_order):
        entries = sorted(
            grouped[(chapter, in_state)],
            key=lambda x: -x[1]["count"],
        )
        ch_label = f"Chapter {chapter}" if chapter else "(unknown chapter)"
        st_label = in_state or "(unknown state)"
        lines.append(f"## {ch_label} — `{st_label}`")
        lines.append("")
        lines.append("| n | composition (HP) | pos_seen | example run |")
        lines.append("|---|---|---|---|")
        for names_str, e in entries:
            hp_str = " + ".join(f"{n}({hp})" for n, hp in (e["monster_hps"] or []))
            pos_str = ", ".join(sorted(e["pos_seen"]))
            if len(pos_str) > 120:
                pos_list = sorted(e["pos_seen"])
                pos_str = f"{pos_list[0]} … {pos_list[-1]} ({len(pos_list)} distinct)"
            lines.append(f"| {e['count']} | {hp_str} | {pos_str} | {e['example_run']} |")
        lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT}")
    print(f"  {len(comps)} unique compositions across {prefight_count} battles "
          f"in {len(run_dirs)} runs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
